-- LEVEL 4: Aggregation + Group BY:
-- Find total quantity ordered for each product:
SELECT 
	p.product_name,
	SUM(quantity) AS total_quantity
FROM products AS p
INNER JOIN orders AS o
ON p.product_id = o.product_id
GROUP BY p.product_name;

-- Find total spending by each customer:
SELECT 
	c.customer_name,
	SUM(price * quantity) AS total_spending
FROM customers AS c
INNER JOIN orders AS o 
ON c.customer_id = o.customer_id
INNER JOIN products AS p
ON p.product_id = o.product_id
GROUP BY c.customer_name;

-- Find total number of orders placed by each customer:
SELECT 
	c.customer_name,
	COUNT(order_id) AS total_orders
FROM customers AS c
INNER JOIN orders AS o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name;

-- Find average product price by category:
SELECT 
	category,
	AVG(price) AS avg_price
FROM products
GROUP BY category;

-- Total revenue generated by each product:
SELECT 
	p.product_name,
	SUM(quantity * price) AS total_revenue
FROM products AS p
LEFT JOIN orders AS o
ON p.product_id = o.product_id
GROUP BY p.product_name;
